#!/bin/bash

extensions=(
    DavidAnson.vscode-markdownlint
    EditorConfig.EditorConfig
    ms-python.python
    ms-python.vscode-pylance
    PKief.material-icon-theme
    ritwickdey.LiveServer
)

if [[ -x "$(command -v code)" ]]; then
    for ext in $extensions
    do
        code --install-extension $ext --force
    done
fi